FROM centos:7

# Install Magento Dependencies
RUN yum install -y \
    curl \
    git \
    gnupg \
    vim \
    wget \
    lynx \
    psmisc \
    unzip \
    tar \
    bash-completion

RUN yum clean all
